apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
- github.com/85matthew/argocd/argocd-operator/base
- github.com/redhat-canada-gitops/catalog/installplan-approver/base

resources:
- namespace.yaml

patchesStrategicMerge:
- patch-target-namespace.yaml
